package cr.ac.una.prograiv.agenda.domain;
// Generated May 25, 2017 9:24:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Reservacion generated by hbm2java
 */
public class Reservacion  implements java.io.Serializable {


     private Integer pkId;
     private Usuario usuario;
     private Viaje viaje;
     private Integer cantidadAsientos;
     private Set<Tiquete> tiquetes = new HashSet<Tiquete>(0);

    public Reservacion() {
    }

	
    public Reservacion(Usuario usuario, Viaje viaje) {
        this.usuario = usuario;
        this.viaje = viaje;
    }
    public Reservacion(Usuario usuario, Viaje viaje, Integer cantidadAsientos, Set<Tiquete> tiquetes) {
       this.usuario = usuario;
       this.viaje = viaje;
       this.cantidadAsientos = cantidadAsientos;
       this.tiquetes = tiquetes;
    }
   
    public Integer getPkId() {
        return this.pkId;
    }
    
    public void setPkId(Integer pkId) {
        this.pkId = pkId;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Viaje getViaje() {
        return this.viaje;
    }
    
    public void setViaje(Viaje viaje) {
        this.viaje = viaje;
    }
    public Integer getCantidadAsientos() {
        return this.cantidadAsientos;
    }
    
    public void setCantidadAsientos(Integer cantidadAsientos) {
        this.cantidadAsientos = cantidadAsientos;
    }
    public Set<Tiquete> getTiquetes() {
        return this.tiquetes;
    }
    
    public void setTiquetes(Set<Tiquete> tiquetes) {
        this.tiquetes = tiquetes;
    }




}


