package cr.ac.una.prograiv.agenda.domain;
// Generated May 25, 2017 9:24:05 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TipoAvion generated by hbm2java
 */
public class TipoAvion  implements java.io.Serializable {


     private Integer pkId;
     private int ano;
     private String modelo;
     private String marca;
     private int cantidadFilas;
     private int cantidadAsientos;
     private int cantidadPasajeros;
     private String ultUsuario;
     private Date ultModificacion;


    public TipoAvion() {
    }

	
    public TipoAvion(int ano, String modelo, String marca, int cantidadFilas, int cantidadAsientos, int cantidadPasajeros) {
        this.ano = ano;
        this.modelo = modelo;
        this.marca = marca;
        this.cantidadFilas = cantidadFilas;
        this.cantidadAsientos = cantidadAsientos;
        this.cantidadPasajeros = cantidadPasajeros;
    }
    public TipoAvion(int ano, String modelo, String marca, int cantidadFilas, int cantidadAsientos, int cantidadPasajeros, String ultUsuario, Date ultModificacion) {
       this.ano = ano;
       this.modelo = modelo;
       this.marca = marca;
       this.cantidadFilas = cantidadFilas;
       this.cantidadAsientos = cantidadAsientos;
       this.cantidadPasajeros = cantidadPasajeros;
       this.ultUsuario = ultUsuario;
       this.ultModificacion = ultModificacion;
    }
   
    public Integer getPkId() {
        return this.pkId;
    }
    
    public void setPkId(Integer pkId) {
        this.pkId = pkId;
    }
    public int getAno() {
        return this.ano;
    }
    
    public void setAno(int ano) {
        this.ano = ano;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public int getCantidadFilas() {
        return this.cantidadFilas;
    }
    
    public void setCantidadFilas(int cantidadFilas) {
        this.cantidadFilas = cantidadFilas;
    }
    public int getCantidadAsientos() {
        return this.cantidadAsientos;
    }
    
    public void setCantidadAsientos(int cantidadAsientos) {
        this.cantidadAsientos = cantidadAsientos;
    }
    public int getCantidadPasajeros() {
        return this.cantidadPasajeros;
    }
    
    public void setCantidadPasajeros(int cantidadPasajeros) {
        this.cantidadPasajeros = cantidadPasajeros;
    }
    public String getUltUsuario() {
        return this.ultUsuario;
    }
    
    public void setUltUsuario(String ultUsuario) {
        this.ultUsuario = ultUsuario;
    }
    public Date getUltModificacion() {
        return this.ultModificacion;
    }
    
    public void setUltModificacion(Date ultModificacion) {
        this.ultModificacion = ultModificacion;
    }
}


