package cr.ac.una.prograiv.agenda.domain;
// Generated May 25, 2017 9:24:05 PM by Hibernate Tools 4.3.1


import java.util.Date;


/**
 * Vuelo generated by hbm2java
 */
public class Vuelo  implements java.io.Serializable {


     private Integer pkId;
     private Avion avion;
     private Ciudad ciudadByFkOrigen;
     private Ciudad ciudadByFkDestino;
     private String ultUsuario;
     private Date ultModificacion;

    public Vuelo() {
    }

	
    public Vuelo(Avion avion, Ciudad ciudadByFkOrigen, Ciudad ciudadByFkDestino) {
        this.avion = avion;
        this.ciudadByFkOrigen = ciudadByFkOrigen;
        this.ciudadByFkDestino = ciudadByFkDestino;
    }
    public Vuelo(Avion avion, Ciudad ciudadByFkOrigen, Ciudad ciudadByFkDestino, String ultUsuario, Date ultModificacion) {
       this.avion = avion;
       this.ciudadByFkOrigen = ciudadByFkOrigen;
       this.ciudadByFkDestino = ciudadByFkDestino;
       this.ultUsuario = ultUsuario;
       this.ultModificacion = ultModificacion;
    }
   
    public Integer getPkId() {
        return this.pkId;
    }
    
    public void setPkId(Integer pkId) {
        this.pkId = pkId;
    }
    public Avion getAvion() {
        return this.avion;
    }
    
    public void setAvion(Avion avion) {
        this.avion = avion;
    }
    public Ciudad getCiudadByFkOrigen() {
        return this.ciudadByFkOrigen;
    }
    
    public void setCiudadByFkOrigen(Ciudad ciudadByFkOrigen) {
        this.ciudadByFkOrigen = ciudadByFkOrigen;
    }
    public Ciudad getCiudadByFkDestino() {
        return this.ciudadByFkDestino;
    }
    
    public void setCiudadByFkDestino(Ciudad ciudadByFkDestino) {
        this.ciudadByFkDestino = ciudadByFkDestino;
    }
    public String getUltUsuario() {
        return this.ultUsuario;
    }
    
    public void setUltUsuario(String ultUsuario) {
        this.ultUsuario = ultUsuario;
    }
    public Date getUltModificacion() {
        return this.ultModificacion;
    }
    
    public void setUltModificacion(Date ultModificacion) {
        this.ultModificacion = ultModificacion;
    }

}


